const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const {chromium}=require('playwright');
const {startServer}=require('./helpers/server.cjs');
const output=path.resolve(process.env.OFFICE_QA_DIR||'docs/qa/office');
const checks=[],errors=[];
let runtime,browser,page;
const delay=ms=>new Promise(resolve=>setTimeout(resolve,ms));
const snapshot=()=>page.evaluate(()=>window.officeScene.snapshot());
async function check(name,run){await run();checks.push(name);console.log('PASS:',name);}
async function eventually(condition,timeout=30000){const end=Date.now()+timeout;while(Date.now()<end){if(await condition())return;await delay(80);}throw new Error('Expected office state did not arrive.');}
async function api(route,method='GET',body){const response=await fetch(runtime.base+route,{method,headers:{'content-type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});const result=await response.json();assert.ok(response.ok,JSON.stringify(result));return result;}
const shot=name=>page.screenshot({path:path.join(output,name),animations:'disabled'});
(async()=>{
 try{
  fs.mkdirSync(output,{recursive:true});runtime=await startServer({extraEnv:{DRY_RUN_DELAY_MS:'150'}});
  browser=await chromium.launch({headless:true,...(process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH?{executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH}:{}),args:['--no-sandbox','--use-angle=swiftshader','--enable-unsafe-swiftshader','--no-zygote']});const context=await browser.newContext({viewport:{width:1440,height:960}});await context.route(/^https?:\/\/(?!127\.0\.0\.1[:/])/,route=>route.abort());page=await context.newPage();page.on('pageerror',error=>errors.push(error.message));
  await check('Landing demo uses local video, branding and a reachable app link',async()=>{await page.goto(runtime.base);assert.ok(await page.locator('video').count()>0);const sources=await page.locator('video source').evaluateAll(nodes=>nodes.map(node=>node.getAttribute('src')));assert.ok(sources.every(source=>source&&!source.startsWith('http')));assert.ok(await page.getByRole('link',{name:'Get Started',exact:true}).count()>0);await shot('landing-1440.png');});
  await check('Office boots with local assets and all canonical employees',async()=>{await page.goto(runtime.base+'/app');await page.waitForFunction(()=>Boolean(window.officeScene));const state=await snapshot(),roster=(await api('/api/agents')).roster;assert.equal(state.team.length,roster.length);for(const employee of state.team)assert.ok(roster.some(person=>person.id===employee.agentId&&person.n===employee.name));});
  await check('Avatars have unique initials and roster-matched identities',async()=>{const state=await snapshot(),roster=(await api('/api/agents')).roster;assert.equal(new Set(state.team.map(person=>person.initials)).size,state.team.length);for(const person of state.team)assert.equal(person.gender,roster.find(employee=>employee.id===person.agentId).gender);assert.equal(await page.locator('.name-label').count(),state.team.length);});
  await check('Floor previews load from rendered local models',async()=>{await page.waitForFunction(()=>document.querySelectorAll('.floor-thumb').length===4);assert.equal(await page.locator('.floor-thumb').evaluateAll(images=>images.every(image=>image.complete&&image.naturalWidth===200)),true);});
  await check('Ambient motion and pause controls reflect actual simulation state',async()=>{if((await snapshot()).routine)await page.locator('#bRoutine').click();assert.equal((await snapshot()).routine,false);if(!(await snapshot()).paused)await page.locator('#bPause').click();assert.equal((await snapshot()).paused,true);assert.equal(await page.locator('#bPause').getAttribute('aria-pressed'),'true');});
  await check('All four floor controls reveal the selected floor and caption',async()=>{for(const floor of [1,2,4,3]){await page.locator(`[data-floor="${floor}"]`).click();await eventually(async()=>!(await snapshot()).transitioning);const state=await snapshot();assert.equal(state.floor,floor);assert.ok(state.visibleFloors.includes(floor));assert.equal(await page.locator(`[data-floor="${floor}"]`).getAttribute('aria-pressed'),'true');}});
  await check('Whole-building view and a model floor click work together',async()=>{await page.locator('[data-floor="0"]').click();await eventually(async()=>!(await snapshot()).transitioning);assert.deepEqual((await snapshot()).visibleFloors,[1,2,3,4]);const point=await page.evaluate(()=>window.officeScene.floorPoint(2));await page.mouse.click(point.x,point.y);await eventually(async()=>!(await snapshot()).transitioning);assert.equal((await snapshot()).floor,2);await page.locator('[data-floor="3"]').click();await eventually(async()=>!(await snapshot()).transitioning);});
  await check('Employee selector opens the exact coworker details',async()=>{await page.locator('#teamSelect').selectOption('Kak Rani');assert.equal(await page.locator('#info h2').innerText(),'Kak Rani');assert.equal(await page.locator('#info').evaluate(element=>element.scrollTop),0);assert.equal(await page.locator('#iScope').inputValue(),'person');});
  await check('Individual lunch command preserves the camera and targets one coworker',async()=>{const before=await snapshot();await page.locator('[data-command=lunch]').click();const after=await snapshot();assert.deepEqual(after.camera,before.camera);assert.deepEqual(after.team.filter(person=>person.destination===2).map(person=>person.name),['Kak Rani']);});
  await check('Division command only targets selected coworkers in that division',async()=>{await page.locator('#iScope').selectOption('division');await page.locator('[data-command=roof]').click();const state=await snapshot(),targets=state.team.filter(person=>person.destination===4);assert.ok(targets.length>1);assert.ok(targets.every(person=>person.group==='marketing'));});
  await check('Custom command selects the requested people and enforces meeting capacity',async()=>{await page.locator('[data-command=work]').click();await page.locator('#iScope').selectOption('custom');await page.locator('#iPeople input[value="Tari"]').check();await page.locator('[data-command=meet]').click();assert.deepEqual((await snapshot()).team.filter(person=>person.activity==='meet').map(person=>person.name).sort(),['Kak Rani','Tari']);await page.locator('#iPeople input').evaluateAll(inputs=>inputs.forEach(input=>input.checked=true));await page.locator('[data-command=meet]').click();assert.match(await page.locator('#sceneStatus').innerText(),/Only 6 places/);assert.equal((await snapshot()).team.filter(person=>person.activity==='meet').length,2);});
  await check('Empty selection offers a useful message and no command runs',async()=>{await page.locator('#iPeople input').evaluateAll(inputs=>inputs.forEach(input=>input.checked=false));const before=await snapshot();await page.locator('[data-command=work]').click();assert.match(await page.locator('#sceneStatus').innerText(),/at least one/);assert.deepEqual((await snapshot()).team.map(person=>person.destination),before.team.map(person=>person.destination));});
  await check('A coworker walks down the stairs to lunch while Tasks is open',async()=>{await page.locator('#iScope').selectOption('person');await page.locator('[data-command=lunch]').click();await page.locator('#bPause').click();await page.locator('[data-organa-route=tasks]').click();await eventually(async()=>{const person=(await snapshot()).team.find(person=>person.name==='Kak Rani');return person.floor===2&&person.state==='break';},90000);await page.locator('#closeTasks').click();await page.locator('#bPause').click();});
  await check('Return to work reaches the coworker desk and keeps the camera',async()=>{const before=(await snapshot()).camera;await page.locator('[data-command=work]').click();await page.locator('#bPause').click();await page.locator('[data-organa-route=tasks]').click();await eventually(async()=>{const person=(await snapshot()).team.find(person=>person.name==='Kak Rani');return person.floor===3&&person.state==='work'&&person.atDesk;},90000);assert.deepEqual((await snapshot()).camera,before);await page.locator('#closeTasks').click();await page.locator('#bPause').click();});
  await check('Task output review is linked to the real coworker in the office',async()=>{const agent=(await api('/api/agents')).agents.find(person=>person.displayName==='Kak Rani');const task=await api('/api/tasks','POST',{title:'Office review task',brief:'Write a short campaign status update and clearly label assumptions.',assigneeAgentId:agent.id,approvalPolicy:'review_output',clientRequestId:'office-ui-task'});await page.locator('[data-organa-route=tasks]').click();await eventually(async()=> (await api('/api/tasks')).find(record=>record.id===task.id).status==='review');await page.evaluate(id=>window.officeTasks.openTask(id),task.id);await page.locator(`[data-task-id="${task.id}"]`).getByRole('button',{name:'Approve & finish',exact:true}).click();await eventually(async()=> (await api('/api/tasks')).find(record=>record.id===task.id).status==='done');await page.locator('#closeTasks').click();await eventually(async()=>['completed','idle'].includes((await snapshot()).team.find(person=>person.agentId===agent.id).workState));});
  await check('Overview and Evaluation return to Office without a duplicate navigation panel',async()=>{for(const route of ['overview','performance']){await page.locator(`[data-organa-route=${route}]`).click();await page.locator('#mcContent:not([aria-busy])').waitFor();assert.equal(await page.locator('#missionDialog nav,#missionDialog #appSidebar').count(),0);await page.locator('[data-organa-route=office]').click();await eventually(async()=>!(await page.locator('#missionDialog').isVisible()));assert.equal(await page.locator('[data-organa-route=office]').getAttribute('aria-current'),'page');}});
  await check('Office and coworker controls fit phone, tablet and desktop widths',async()=>{for(const width of [320,390,768,1440]){await page.setViewportSize({width,height:width<640?844:960});await page.locator('#teamSelect').selectOption('Kak Rani');assert.equal(await page.locator('#info').evaluate(element=>element.scrollWidth<=element.clientWidth+1),true);assert.equal(await page.locator('#info').evaluate(element=>element.scrollTop),0);const panel=await page.locator('#info').boundingBox(),controls=await page.locator('#controls').boundingBox();await eventually(async()=>{const panel=await page.locator('#info').boundingBox(),controls=await page.locator('#controls').boundingBox();return panel.y+panel.height<=controls.y+1;});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true);if([390,1440].includes(width))await shot(`office-${width}.png`);}});
  await check('Music starts, changes volume, and stops with explicit controls',async()=>{await page.locator('#bMusic').click();await eventually(async()=>await page.evaluate(()=>window.officeMusic.snapshot().state==='running'));await page.locator('#musicVolume').focus();await page.keyboard.press('Home');for(let step=0;step<10;step++)await page.keyboard.press('ArrowRight');assert.equal(await page.evaluate(()=>window.officeMusic.snapshot().volume),10);await page.locator('#bMusic').click();await eventually(async()=>await page.evaluate(()=>window.officeMusic.snapshot().state==='suspended'));});
  await check('Office, landing and modal journeys produce no uncaught browser errors',async()=>{assert.deepEqual(errors,[]);});
  fs.writeFileSync(path.join(output,'office-ui-results.json'),JSON.stringify({version:require('../package.json').version,verifiedAt:new Date().toISOString(),passed:checks.length,checks,mode:'deterministic-demo',uncaughtErrors:errors},null,2)+'\n');console.log(`${checks.length} Office and landing checks passed.`);
 }catch(error){if(page)await shot('failure.png').catch(()=>{});throw error;}finally{await browser?.close();await runtime?.cleanup();}
})().catch(error=>{console.error(error);process.exitCode=1;});
