const assert=require('node:assert/strict');
const fs=require('node:fs');
const os=require('node:os');
const path=require('node:path');
const {chromium}=require('playwright');
const {startServer}=require('./helpers/server.cjs');
const {nusaDemoState}=require('../server/data/default-state');
const output=path.resolve(process.env.UI_QA_DIR||'docs/qa/ui');
const checks=[],errors=[],layouts=[];
let runtime,browser,page;
const pause=ms=>new Promise(resolve=>setTimeout(resolve,ms));
async function check(name,run){await run();checks.push(name);console.log('PASS:',name);}
async function eventually(condition,timeout=15000){const until=Date.now()+timeout;while(Date.now()<until){if(await condition())return;await pause(80);}throw new Error('Expected UI state did not appear.');}
async function api(route,method='GET',body){const response=await fetch(runtime.base+route,{method,headers:{'content-type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});const result=await response.json();assert.ok(response.ok,`${method} ${route}: ${JSON.stringify(result)}`);return result;}
const routes={company:'overview',mission:'missions',review:'approvals'};
async function tab(name){await page.locator(`[data-organa-route="${routes[name]||name}"]`).click();await page.locator(`#mcContent[data-view="${name}"]:not([aria-busy])`).waitFor();}
const shot=name=>page.screenshot({path:path.join(output,name),animations:'disabled'});
const normalize=value=>String(value).replace(/\s+/g,' ').trim();

(async()=>{
 const dataDir=fs.mkdtempSync(path.join(os.tmpdir(),'organa-ui-'));
 try{
  fs.mkdirSync(output,{recursive:true});const seed=nusaDemoState(),createdAt=new Date().toISOString();
  const fixture=(id,title,assignee,status,extra={})=>({id,title,companyId:seed.activeCompanyId,assigneeAgentId:assignee,assignee:seed.agents.find(a=>a.id===assignee).displayName,status,brief:'A saved task for reassignment regression.',version:1,dependencyIds:[],goalIds:[],approvalPolicy:'review_output',createdAt,updatedAt:createdAt,...extra});
  seed.tasks.push(fixture('ui-blocker','UI upstream blocker','agt_product','failed',{error:'Fixture provider failure'}),fixture('ui-assignment','UI dependent assignment','agt_finance','waiting_dependency',{dependencyIds:['ui-blocker']}));
  seed.projects.push({id:'ui-clarification',companyId:seed.activeCompanyId,title:'UI clarification mission',objective:'Prepare a coffee pilot with the confirmed budget.',goalIds:[],status:'needs_input',planVersion:1,planDraft:{tasks:[],meetings:[],clarifyingQuestions:['What is the pilot budget?']},createdAt,updatedAt:createdAt});
  fs.writeFileSync(path.join(dataDir,'state.json'),JSON.stringify(seed));
  runtime=await startServer({dataDir,extraEnv:{DRY_RUN_DELAY_MS:'50'}});
  const plans=await Promise.all(['UI Alpha launch','UI Beta research'].map(goal=>api('/api/projects/plan','POST',{goal,clientRequestId:goal})));
  await api(`/api/projects/${plans[0].id}/activate-plan`,'POST',{});
  await eventually(async()=> (await api('/api/approvals?status=pending')).length>0);
  browser=await chromium.launch({headless:true,...(process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH?{executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH}:{}),args:['--no-sandbox','--use-angle=swiftshader','--enable-unsafe-swiftshader','--no-zygote']});
  const context=await browser.newContext({viewport:{width:1440,height:960}});await context.route(/^https?:\/\/(?!127\.0\.0\.1[:/])/,route=>route.abort());
  page=await context.newPage();page.on('pageerror',error=>errors.push(error.message));await page.goto(runtime.base+'/app');await page.waitForFunction(()=>Boolean(window.officeScene));
  await check('All ten workspace pages fit five viewport widths with one global navigation',async()=>{
   for(const width of [320,390,768,1024,1440]){await page.setViewportSize({width,height:width<640?844:960});for(const name of ['company','mission','team','meetings','knowledge','review','standup','goals','performance','settings']){await tab(name);const layout=await page.evaluate(()=>({viewport:innerWidth,document:document.documentElement.scrollWidth,content:document.getElementById('mcContent').clientWidth,scroll:document.getElementById('mcContent').scrollWidth,headings:document.querySelectorAll('#missionDialog h1').length,innerNav:document.querySelectorAll('#missionDialog nav,#missionDialog .mc-tabs,#missionDialog #appSidebar').length}));assert.ok(layout.document<=width+1,`${name} page overflows at ${width}`);assert.ok(layout.scroll<=layout.content+1,`${name} content overflows at ${width}`);assert.equal(layout.headings,1);assert.equal(layout.innerNav,0);layouts.push({page:name,width,...layout});if([390,1440].includes(width))await shot(`${name}-${width}.png`);}}
  });
  await check('Overview counters and knowledge action open the matching feature',async()=>{
   await tab('company');await page.locator('.mc-hero-stat-link').filter({hasText:'active AI coworkers'}).click();await page.locator('#mcContent[data-view=team]:not([aria-busy])').waitFor();await tab('company');await page.locator('.mc-hero-stat-link').filter({hasText:'decisions need you'}).click();await page.locator('#mcContent[data-view=review]:not([aria-busy])').waitFor();await tab('performance');const person=page.locator('[data-evaluation-agent-id]').first(),id=await person.getAttribute('data-evaluation-agent-id');await person.getByRole('button',{name:'View coworker',exact:true}).click();await page.locator(`.mc-team-profile[data-agent-id="${id}"]`).waitFor();
  });
  await check('Mission and meeting search hide records without rebuilding their forms',async()=>{
   for(const [name,label,selector] of [['mission','missions','.mc-mission-card'],['meetings','meetings','.mc-meeting-card']]){await tab(name);const count=await page.locator(selector).count();assert.ok(count>0);await page.getByRole('searchbox',{name:`Search ${label}`,exact:true}).fill('NoMatchingRecord987');await page.getByText('No matching results',{exact:true}).waitFor();assert.equal(await page.locator(`${selector}:visible`).count(),0);await page.getByRole('button',{name:'Clear filters',exact:true}).click();assert.equal(await page.locator(`${selector}:visible`).count(),count);}
   await tab('mission');await page.getByRole('searchbox',{name:'Search missions',exact:true}).fill('UI Alpha');assert.equal(await page.locator('.mc-mission-card:visible').count(),1);
  });
  await check('Mission clarification retains its draft after reload and failed save, then updates the same mission',async()=>{
   await tab('mission');const record=page.locator('[data-project-id=ui-clarification]');await page.getByRole('searchbox',{name:'Search missions',exact:true}).fill('UI clarification');await record.getByLabel('Your answer',{exact:true}).fill('Use IDR 5 million for a two-week pilot.');await shot('clarification-1440.png');await tab('company');await page.reload();await page.waitForFunction(()=>Boolean(window.officeScene));await tab('mission');assert.equal(await record.getByLabel('Your answer',{exact:true}).inputValue(),'Use IDR 5 million for a two-week pilot.');
   const failing=route=>route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:'Clarification save unavailable. Try again.'})});await page.route('**/api/projects/ui-clarification/answer',failing);await record.getByRole('button',{name:'Update mission plan',exact:true}).click();await page.getByText('Clarification save unavailable. Try again.',{exact:true}).first().waitFor();assert.equal(await record.getByLabel('Your answer',{exact:true}).inputValue(),'Use IDR 5 million for a two-week pilot.');await page.unroute('**/api/projects/ui-clarification/answer',failing);await record.getByRole('button',{name:'Update mission plan',exact:true}).click();await record.getByRole('button',{name:'Start Mission',exact:true}).waitFor();const saved=await api('/api/projects/ui-clarification');assert.equal(saved.planVersion,2);assert.equal(saved.clarificationHistory.length,1);assert.equal(saved.status,'draft_plan');assert.equal(await record.getByLabel('Your answer',{exact:true}).count(),0);
  });
  await check('Starting a mission while navigating away preserves the selected workspace and starts one task set',async()=>{
   await tab('mission');await page.getByRole('searchbox',{name:'Search missions',exact:true}).fill('UI Beta');const id=plans[1].id,record=page.locator(`[data-project-id="${id}"]`);let release,entered=false;const gate=new Promise(resolve=>release=resolve),delayed=async route=>{entered=true;await gate;await route.continue();};await page.route(`**/api/projects/${id}/activate-plan`,delayed);await record.getByRole('button',{name:'Start Mission',exact:true}).click();await eventually(()=>entered);assert.equal(await record.getByRole('button',{name:'Start Mission',exact:true}).isDisabled(),true);await tab('performance');release();await eventually(async()=> (await api(`/api/projects/${id}`)).status!=='draft_plan');await pause(300);assert.equal(await page.locator('#mcContent').getAttribute('data-view'),'performance');await page.unroute(`**/api/projects/${id}/activate-plan`,delayed);const first=await api(`/api/projects/${id}/activate-plan`,'POST',{}),second=await api(`/api/projects/${id}/activate-plan`,'POST',{});assert.deepEqual(first.tasks.map(task=>task.id),second.tasks.map(task=>task.id));assert.equal((await api('/api/tasks')).filter(task=>task.projectId===id).length,first.tasks.length);
  });
  await check('Approval revision draft survives filtering and navigation',async()=>{
   await tab('review');const record=page.locator('.mc-approval-record').first(),id=await record.getAttribute('data-approval-id');await record.getByRole('button',{name:'Request revision',exact:true}).click();await record.getByLabel('Revision feedback',{exact:true}).fill('Keep my careful review draft.');await page.getByRole('searchbox',{name:'Search approvals',exact:true}).fill('NoMatch');await page.getByRole('button',{name:'Clear filters',exact:true}).click();assert.equal(await record.getByLabel('Revision feedback',{exact:true}).inputValue(),'Keep my careful review draft.');await tab('company');await tab('review');await page.locator(`[data-approval-id="${id}"]`).getByRole('button',{name:'Request revision',exact:true}).click();assert.equal(await page.getByLabel('Revision feedback',{exact:true}).inputValue(),'Keep my careful review draft.');
  });
  await check('Approval source opens the exact task and returns to the same review workspace',async()=>{
   await tab('review');const approval=(await api('/api/approvals?status=pending')).find(record=>record.entityType==='task');assert.ok(approval);const row=page.locator(`[data-approval-id="${approval.id}"]`);await row.getByRole('button',{name:'Open task',exact:true}).click();await page.locator(`[data-task-id="${approval.entityId}"]`).waitFor();assert.equal(await page.locator('#missionDialog').getAttribute('open'),'');await page.keyboard.press('Escape');await eventually(async()=>await page.locator('[data-organa-route=approvals]').getAttribute('aria-current')==='page');
  });
  await check('People search and structure view preserve employee configuration edits',async()=>{
   await tab('team');await page.getByRole('button',{name:'People',exact:true}).click();await page.getByRole('searchbox',{name:'Search team',exact:true}).fill('Maya');assert.equal(await page.locator('.mc-directory-person:visible').count(),1);await page.locator('.mc-directory-person:visible').click();const profile=page.locator('.mc-team-profile');await profile.getByText('Configuration',{exact:true}).click();await profile.getByLabel('Display name',{exact:true}).fill('Maya draft only');await page.getByRole('searchbox',{name:'Search team',exact:true}).fill('Rani');assert.equal(await profile.getByLabel('Display name',{exact:true}).inputValue(),'Maya draft only');await page.getByRole('searchbox',{name:'Search team',exact:true}).fill('');await page.locator('#mcContent').evaluate(element=>element.scrollTop=0);await page.getByRole('searchbox',{name:'Search team',exact:true}).evaluate(element=>element.blur());await profile.getByText('Configuration',{exact:true}).click();await profile.evaluate(element=>element.scrollTop=0);await page.locator('#mcContent').evaluate(element=>element.scrollTop=0);await shot('people-1440.png');await page.setViewportSize({width:390,height:844});await page.locator('#mcContent').evaluate(element=>element.scrollTop=0);await shot('people-390.png');await page.setViewportSize({width:1440,height:960});await page.getByRole('button',{name:'Structure',exact:true}).click();await tab('company');await tab('team');assert.equal(await profile.getByLabel('Display name',{exact:true}).inputValue(),'Maya draft only');
  });
  await check('Mission and North Star drafts survive route changes and reload',async()=>{
   await tab('mission');await page.getByLabel('What do you need the organization to solve?',{exact:true}).fill('Preserve this outcome draft');await tab('goals');await page.getByRole('button',{name:'Edit North Star',exact:true}).click();await page.getByLabel('Mission',{exact:true}).fill('A careful draft of the company direction.');await page.getByRole('button',{name:'Back to goals',exact:true}).click();await page.getByRole('button',{name:'Edit North Star',exact:true}).click();assert.equal(await page.getByLabel('Mission',{exact:true}).inputValue(),'A careful draft of the company direction.');await page.reload();await page.waitForFunction(()=>Boolean(window.officeScene));await tab('mission');assert.equal(await page.getByLabel('What do you need the organization to solve?',{exact:true}).inputValue(),'Preserve this outcome draft');await tab('goals');await page.getByRole('button',{name:'Edit North Star',exact:true}).click();assert.equal(await page.getByLabel('Mission',{exact:true}).inputValue(),'A careful draft of the company direction.');
  });
  await check('Settings guidance is collapsed and every mobile route remains reachable',async()=>{
   await tab('settings');const guide=page.locator('.mc-connection-guide');assert.equal(await guide.getAttribute('open'),null);await guide.locator('summary').click();assert.ok(await guide.getByText('GOOGLE_APPLICATION_CREDENTIALS',{exact:false}).count()>0);await guide.locator('summary').click();await page.setViewportSize({width:320,height:844});const menu=page.locator('#organaMobileMenu');await menu.click();assert.equal(await menu.getAttribute('aria-expanded'),'true');assert.equal(await page.locator('[data-organa-route]:visible').count(),12);const settings=await page.locator('[data-organa-route=settings]').boundingBox();assert.ok(settings.y>=0&&settings.y+settings.height<=844);await shot('mobile-all-pages.png');await page.keyboard.press('Escape');assert.equal(await menu.getAttribute('aria-expanded'),'false');assert.equal(await page.locator('#missionDialog').getAttribute('open'),'');await page.setViewportSize({width:1440,height:960});
  });
  await check('Task search and native modal close return to the previous workspace',async()=>{
   await tab('settings');await page.locator('[data-organa-route=tasks]').click();assert.ok(await page.locator('#taskDialog').evaluate(element=>element.matches(':modal')));assert.equal(await page.locator('#taskDialog nav,#taskDialog aside').count(),0);await page.getByRole('searchbox',{name:'Search tasks',exact:true}).fill('NoMatchingTask');assert.equal(await page.locator('.task-item').count(),0);await page.getByRole('searchbox',{name:'Search tasks',exact:true}).fill('');assert.ok(await page.locator('.task-item').count()>0);await shot('tasks-1440.png');await page.setViewportSize({width:390,height:844});await shot('tasks-390.png');assert.equal(await page.locator('#taskDialog').evaluate(element=>element.scrollWidth<=element.clientWidth+1),true);await page.locator('#closeTasks').click();await eventually(async()=>await page.locator('[data-organa-route=settings]').getAttribute('aria-current')==='page');await page.setViewportSize({width:1440,height:960});
  });
  await check('Assignee choice survives polling, rename, failed save and a newer choice during save',async()=>{
   await page.locator('[data-organa-route=tasks]').click();let select=page.getByRole('combobox',{name:'New assignee for UI dependent assignment',exact:true});await select.selectOption('agt_research');await api('/api/agents/agt_research','PATCH',{displayName:'Maya UI'});await eventually(async()=>await select.locator('option:checked').textContent()==='Maya UI');assert.equal(await select.inputValue(),'agt_research');const task=page.locator('[data-task-id=ui-assignment]');const failing=route=>route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:'Save unavailable. Try again.'})});await page.route('**/api/tasks/ui-assignment',failing);await task.getByRole('button',{name:'Move task',exact:true}).click();await page.getByText('Save unavailable. Try again.',{exact:true}).waitFor();assert.equal(await select.inputValue(),'agt_research');await page.unroute('**/api/tasks/ui-assignment',failing);
   let release,entered=false;const gate=new Promise(resolve=>release=resolve),delayed=async route=>{entered=true;await gate;await route.continue();};await page.route('**/api/tasks/ui-assignment',delayed);await task.getByRole('button',{name:'Move task',exact:true}).click();await eventually(()=>entered);await select.selectOption('agt_marketing');release();await eventually(async()=> (await api('/api/tasks')).find(item=>item.id==='ui-assignment').assigneeAgentId==='agt_research');await eventually(async()=>!(await task.getByRole('button',{name:'Move task',exact:true}).isDisabled()));assert.equal(await select.inputValue(),'agt_marketing');await page.unroute('**/api/tasks/ui-assignment',delayed);await task.getByRole('button',{name:'Move task',exact:true}).click();await eventually(async()=> (await api('/api/tasks')).find(item=>item.id==='ui-assignment').assigneeAgentId==='agt_marketing');const saved=(await api('/api/tasks')).find(item=>item.id==='ui-assignment');assert.equal(saved.status,'waiting_dependency');await page.keyboard.press('Escape');
  });
  await check('Task and Knowledge documents format safely and show the current version',async()=>{
   const source='# Launch recommendation\nUse **verified evidence** and `bounded budgets`.\n- Run a Jakarta pilot\n- Review results\n| Channel | Budget |\n| --- | --- |\n| Search | 2000000 |\n```text\n<literal code>\n```\n<img src=x onerror="window.uiInjected=true">\n[Unsafe link](javascript:alert(1))';
   const tasksHandler=async route=>{const response=await route.fetch(),tasks=await response.json();tasks.push({...fixture('ui-document','Formatted document','agt_research','done'),result:source});await route.fulfill({response,json:tasks});};const deliveriesHandler=route=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify([{id:'ui-doc',title:'Current decision document',status:'approved',currentVersionId:'v2',versions:[{id:'v1',content:'OUTDATED'},{id:'v2',content:source}]}])});await page.route('**/api/tasks',tasksHandler);await page.route('**/api/deliverables',deliveriesHandler);await page.evaluate(()=>window.officeTasks.openTask('ui-document'));const document=page.locator('[data-task-id=ui-document] .organa-document');await document.getByRole('heading',{name:'Launch recommendation',exact:true}).waitFor();assert.equal(await document.locator('table').count(),1);assert.equal(await document.locator('img,script,iframe,a[href^="javascript:"]').count(),0);assert.equal(await page.evaluate(()=>Boolean(window.uiInjected)),false);await page.keyboard.press('Escape');await tab('knowledge');const current=page.locator('.mc-knowledge-card .organa-document');await current.getByRole('heading',{name:'Launch recommendation',exact:true}).waitFor();assert.equal(await page.getByText('OUTDATED',{exact:true}).count(),0);await page.getByRole('searchbox',{name:'Search knowledge',exact:true}).fill('NoDocument987');await page.getByRole('button',{name:'Clear search',exact:true}).click();assert.ok(normalize(await current.textContent()).includes('verified evidence'));await shot('document-1440.png');await page.setViewportSize({width:320,height:844});await shot('document-320.png');assert.equal(await page.locator('#mcContent').evaluate(element=>element.scrollWidth<=element.clientWidth+1),true);await page.unroute('**/api/tasks',tasksHandler);await page.unroute('**/api/deliverables',deliveriesHandler);
  });
  await check('Reduced motion disables decorative loading and no uncaught browser errors occur',async()=>{
   await page.emulateMedia({reducedMotion:'reduce'});const handler=async route=>{await pause(350);await route.continue();};await page.route('**/api/company',handler);await page.locator('[data-organa-route=overview]').click();await page.locator('.mc-loading-orbit').waitFor();assert.equal(await page.locator('.mc-loading-orbit').evaluate(element=>getComputedStyle(element).animationName),'none');await page.locator('#mcContent[data-view=company]:not([aria-busy])').waitFor();await page.unroute('**/api/company',handler);assert.deepEqual(errors,[]);
  });
  fs.writeFileSync(path.join(output,'workspace-ui-results.json'),JSON.stringify({version:require('../package.json').version,verifiedAt:new Date().toISOString(),mode:'deterministic-demo',passed:checks.length,checks,layouts,uncaughtErrors:errors,documentFixtureScope:'Formatting and unsafe-content rendering only; not evidence of live model output quality.'},null,2)+'\n');console.log(`${checks.length} UI checks and ${layouts.length} layout combinations passed.`);
 }catch(error){if(page)await shot('failure.png').catch(()=>{});throw error;}
 finally{await browser?.close();await runtime?.cleanup();fs.rmSync(dataDir,{recursive:true,force:true});}
})().catch(error=>{console.error(error);process.exitCode=1;});
