const assert=require('node:assert/strict');
const fs=require('node:fs');
const os=require('node:os');
const path=require('node:path');
const net=require('node:net');
const {spawn}=require('node:child_process');
const {redactor,positive,preflight}=require('./lib/live-check-support.cjs');
const {nusaDemoState}=require('../server/data/default-state');
const root=path.resolve(__dirname,'..');
const delay=ms=>new Promise(resolve=>setTimeout(resolve,ms));
async function freePort(){const server=net.createServer();await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const port=server.address().port;await new Promise(resolve=>server.close(resolve));return port;}
async function main(args=process.argv.slice(2)){
 const allowed=new Set(['--preflight','--fixture','--help']);if(args.some(arg=>!allowed.has(arg)))throw new Error('Unknown option. Use --help.');
 if(args.includes('--help')){console.log('npm run test:live -- [--preflight]\nUses your local server-side Gemini configuration with isolated test data.');return;}
 const config=require('../server/config'),safe=redactor(),selection=preflight(config,{fixture:args.includes('--fixture')}),maxCalls=positive(process.env.ORGANA_LIVE_CHECK_MAX_CALLS,30,200),maxTokens=positive(process.env.ORGANA_LIVE_CHECK_MAX_TOKENS,8192,32768);
 if(args.includes('--preflight')){console.log(`Local configuration ready for ${selection.provider}. Authentication has not been tested. No model request was sent.`);return;}
 const output=path.resolve(process.env.ORGANA_LIVE_CHECK_OUTPUT||path.join(root,'.local-qa',`live-${new Date().toISOString().replace(/[:.]/g,'-')}`));fs.mkdirSync(output,{recursive:true});
 const dataDir=fs.mkdtempSync(path.join(os.tmpdir(),'organa-live-')),budgetPath=path.join(output,'budget.json'),checks=[];let child,base,logs='',cancelled=false;
 const report={version:require('../package.json').version,provider:selection.provider,fixture:selection.fixture,liveExecutionVerified:false,startedAt:new Date().toISOString(),limits:{maxCalls,maxTokens,timeoutMinutes:20},checks};
 const save=()=>{report.completedAt=new Date().toISOString();report.passed=checks.filter(check=>check.passed).length;try{report.modelCallsReserved=JSON.parse(fs.readFileSync(budgetPath)).calls;}catch{report.modelCallsReserved=0;}fs.writeFileSync(path.join(output,'results.json'),safe(JSON.stringify(report,null,2))+'\n');fs.writeFileSync(path.join(output,'report.md'),safe(`# Organa local workflow check\n\nProvider: ${selection.provider}\nMode: ${selection.fixture?'Fixture harness, no live AI':'Live Gemini'}\nPassed: ${report.passed}/${checks.length}\nLive execution verified: ${report.liveExecutionVerified}\n\n${checks.map(check=>`- ${check.passed?'PASS':'FAIL'}: ${check.name}${check.error?` (${check.error})`:''}`).join('\n')}\n\n${report.error||''}\n`).trimEnd()+'\n');};
 async function stop(){if(child&&child.exitCode===null&&child.signalCode===null){child.kill('SIGTERM');await new Promise(resolve=>{child.once('exit',resolve);const timer=setTimeout(()=>{child.kill('SIGKILL');resolve();},3000);timer.unref();});}}
 const interrupt=()=>{cancelled=true;void stop();};process.on('SIGINT',interrupt);process.on('SIGTERM',interrupt);const timer=setTimeout(interrupt,20*60*1000);timer.unref();
 async function request(route,method='GET',body,expected){if(cancelled)throw new Error('Live check cancelled.');const response=await fetch(base+route,{method,headers:{'content-type':'application/json'},body:body===undefined?undefined:JSON.stringify(body),signal:AbortSignal.timeout(100000)});const data=await response.json();if(expected!==undefined)assert.equal(response.status,expected);else if(!response.ok)throw new Error(`${method} ${route}: ${data.error||response.status}`);return data;}
 async function check(name,run){const entry={name,passed:false};checks.push(entry);try{await run();entry.passed=true;console.log(`PASS: ${name}`);}catch(error){entry.error=safe(error.message);throw error;}finally{save();}}
 async function until(run,timeout=150000){const end=Date.now()+timeout;while(Date.now()<end){if(cancelled)throw new Error('Live check cancelled.');const result=await run();if(result)return result;await delay(300);}throw new Error('The expected workflow state did not arrive.');}
 async function launch(){const port=await freePort();base=`http://127.0.0.1:${port}`;child=spawn(process.execPath,['-r',path.join(root,'scripts/live-provider-guard.cjs'),'server/server.js'],{cwd:root,env:{...process.env,ENV_FILE:'/nonexistent',PORT:String(port),HOST:'127.0.0.1',DATA_DIR:dataDir,ORGANA_STORAGE:'json',ORGANA_DRY_RUN:selection.fixture?'1':'0',ORGANA_LLM_PROVIDER:selection.provider,ORGANA_LIVE_CHECK_BUDGET_FILE:budgetPath,ORGANA_LIVE_CHECK_MAX_CALLS:String(maxCalls),ORGANA_LIVE_CHECK_MAX_TOKENS:String(maxTokens),DRY_RUN_DELAY_MS:'5'},stdio:['ignore','pipe','pipe']});for(const stream of [child.stdout,child.stderr])stream.on('data',chunk=>{logs=safe((logs+chunk.toString()).slice(-12000));});await until(async()=>{if(child.exitCode!==null)throw new Error('The isolated test server exited.');try{return await request('/api/health');}catch{return false;}},15000);}
 try{
  fs.writeFileSync(path.join(dataDir,'state.json'),JSON.stringify(nusaDemoState()));fs.writeFileSync(budgetPath,JSON.stringify({calls:0}));await launch();let task,project,activation,meeting,approval;
  await check('Health uses the selected provider and isolated JSON storage',async()=>{const health=await request('/api/health');assert.equal(health.provider,selection.provider);assert.equal(health.storage,'json');});
  await check('Company and reviewed team are available',async()=>{assert.equal((await request('/api/company')).company.name,'Nusa Coffee');assert.ok((await request('/api/agents')).agents.length>=2);});
  await check('Direct instruction executes and returns a reviewable result',async()=>{task=await request('/api/tasks','POST',{title:'Coffee pilot recommendation',brief:'Recommend a small Jakarta coffee launch pilot within IDR 2,000,000. Use available evidence and label assumptions. Return a concise reviewable recommendation.',assigneeAgentId:'agt_research',approvalPolicy:'review_output',clientRequestId:'live-direct'});task=await until(async()=>{const tasks=await request('/api/tasks'),current=tasks.find(item=>item.id===task.id);if(current.status==='failed')throw new Error(current.error);if(current.status==='blocked')throw new Error('The test instruction needs clarification. Review the saved questions locally.');return current.status==='review'&&current;});assert.ok(task.result?.trim());});
  await check('Retry of the same instruction keeps one task',async()=>{const same=await request('/api/tasks','POST',{title:'Coffee pilot recommendation',brief:'Recommend a small Jakarta coffee launch pilot within IDR 2,000,000. Use available evidence and label assumptions. Return a concise reviewable recommendation.',assigneeAgentId:'agt_research',approvalPolicy:'review_output',clientRequestId:'live-direct'});assert.equal(same.id,task.id);});
  await check('Task revision keeps draft history',async()=>{await request(`/api/tasks/${task.id}`,'PATCH',{action:'revise',feedback:'Focus the recommendation on a Jakarta pilot with explicit assumptions and a maximum IDR 2,000,000 budget.',version:task.version});task=await until(async()=>{const current=(await request('/api/tasks')).find(item=>item.id===task.id);if(current.status==='failed')throw new Error(current.error);return current.status==='review'&&current;});assert.ok(task.history?.length>=2);});
  await check('Current task output requires human approval',async()=>{await request(`/api/tasks/${task.id}`,'PATCH',{action:'approve',version:task.version});assert.equal((await request('/api/tasks')).find(item=>item.id===task.id).status,'done');});
  await check('Knowledge retains the approved deliverable and provenance',async()=>{const deliveries=await request('/api/deliverables'),deliverable=deliveries.find(item=>item.taskIds?.includes(task.id));assert.ok(deliverable);assert.equal(deliverable.status,'approved');assert.equal((await request(`/api/deliverables/${deliverable.id}/why`)).deliverableId,deliverable.id);});
  await check('Chief of Staff produces a bounded mission plan',async()=>{project=await request('/api/projects/plan','POST',{goal:'Prepare an evidence-backed Jakarta coffee pilot launch recommendation within IDR 2,000,000. Use a small set of specialist tasks and a meeting to reconcile trade-offs. Return a ready-to-review plan without questions.',clientRequestId:'live-plan'});assert.equal(project.status,'draft_plan');assert.ok(project.planDraft.tasks.length<=8);});
  await check('Plan retry returns the same saved project',async()=>{const same=await request('/api/projects/plan','POST',{goal:project.objective,clientRequestId:'live-plan'});assert.equal(same.id,project.id);});
  await check('Activation retry preserves task and meeting identities',async()=>{activation=await request(`/api/projects/${project.id}/activate-plan`,'POST',{});const again=await request(`/api/projects/${project.id}/activate-plan`,'POST',{});assert.deepEqual(activation.tasks.map(item=>item.id),again.tasks.map(item=>item.id));});
  await check('Mission tasks execute in dependency order and each draft is reviewed',async()=>{await until(async()=>{const tasks=(await request('/api/tasks')).filter(item=>item.projectId===project.id);for(const item of tasks){if(item.status==='failed')throw new Error(item.error);if(item.status==='blocked')throw new Error('A mission task needs additional human input.');if(item.status==='review')await request(`/api/tasks/${item.id}`,'PATCH',{action:'approve',version:item.version});}return tasks.length&&tasks.every(item=>item.status==='done');},300000);});
  await check('A cross-functional meeting produces a decision for review',async()=>{meeting=(await request('/api/meetings')).find(item=>item.projectId===project.id);assert.ok(meeting,'The plan did not create a cross-functional meeting.');meeting=await request(`/api/meetings/${meeting.id}/start`,'POST',{});assert.equal(meeting.status,'review');assert.ok(meeting.contributions.length>=2);approval=meeting.approvalId;});
  await check('Approval Center confirms the exact meeting decision',async()=>{await request(`/api/approvals/${approval}/approve`,'POST',{});assert.equal((await request(`/api/meetings/${meeting.id}`)).status,'completed');});
  await check('Previously resolved approval cannot approve another version',async()=>{await request(`/api/approvals/${approval}/approve`,'POST',{},409);});
  await check('Stand-up has verified links to saved work',async()=>{const brief=await request('/api/standups/generate','POST',{});assert.ok(brief.summary.headline);assert.ok(brief.summary.completed.some(item=>item.ref===`task:${task.id}`));});
  await check('Usage and events record provider-backed execution',async()=>{const usage=await request('/api/usage/summary');assert.ok(usage.requests>0);assert.ok((await request('/api/events?limit=200')).some(event=>event.type==='task.completed'));if(!selection.fixture)assert.ok(JSON.parse(fs.readFileSync(budgetPath)).calls>0);});
  await check('Restart retains task results, meeting decisions, stand-up and budget',async()=>{const before=JSON.parse(fs.readFileSync(budgetPath)).calls;await stop();await launch();assert.equal((await request('/api/tasks')).find(item=>item.id===task.id).status,'done');assert.equal((await request(`/api/meetings/${meeting.id}`)).status,'completed');assert.ok((await request('/api/standups/latest')).summary);assert.equal(JSON.parse(fs.readFileSync(budgetPath)).calls,before);});
  report.liveExecutionVerified=!selection.fixture;report.success=true;save();console.log(`Results saved to ${path.relative(root,output)}. Live execution verified: ${report.liveExecutionVerified}.`);
 }catch(error){report.error=safe(error.message);report.success=false;report.cancelled=cancelled;save();throw new Error(report.error);}
 finally{clearTimeout(timer);process.removeListener('SIGINT',interrupt);process.removeListener('SIGTERM',interrupt);await stop();fs.rmSync(dataDir,{recursive:true,force:true});}
 return report;
}
if(require.main===module)main().catch(error=>{console.error(redactor()(error.message));process.exitCode=1;});
module.exports={main};
