const {id,now,activeNorthStar}=require('./helpers');
class DeliverableService{
 constructor({stateManager,eventService}){Object.assign(this,{stateManager,eventService});}
 create({title,type='document',content='',structuredData=null,createdBy,taskIds=[],goalIds=[],projectId=null,evidenceRefs=[],assumptions=[],uncertainties=[],goalAlignment=[],constraintChecks=[],collaboratorAgentIds=[],decisionSummary='',status='ready',northStarVersion=null,agentPromptVersion=null}){
  const s=this.stateManager.get(),createdAt=now(),versionId=id('dlv');const d={id:id('del'),companyId:s.activeCompanyId,projectId,title,type,status,currentVersionId:versionId,createdBy,taskIds,goalIds,collaboratorAgentIds,why:{evidenceRefs,assumptions,uncertainties,goalAlignment,constraintChecks,decisionSummary,northStarVersion:northStarVersion??activeNorthStar(s)?.version??null,agentPromptVersion:agentPromptVersion??null},versions:[{id:versionId,version:1,content,structuredData,createdBy,createdAt}],createdAt,updatedAt:createdAt};s.deliverables.push(d);this.eventService.append('deliverable.created',{actor:createdBy,entity:{type:'deliverable',id:d.id},goalIds,projectId,payload:{title,type,status}});return d;
 }
 list(){const s=this.stateManager.get();return(s.deliverables||[]).filter(d=>d.companyId===s.activeCompanyId).sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt));}
 get(deliverableId){const s=this.stateManager.get();return(s.deliverables||[]).find(d=>d.companyId===s.activeCompanyId&&d.id===deliverableId)||null;}
 why(deliverableId){const d=this.get(deliverableId);if(!d)throw Object.assign(new Error('Deliverable not found.'),{status:404});const s=this.stateManager.get();const goals=(s.goals||[]).filter(g=>(d.goalIds||[]).includes(g.id));const collaborators=(s.agents||[]).filter(a=>(d.collaboratorAgentIds||[]).includes(a.id)).map(a=>({id:a.id,displayName:a.displayName,role:a.role}));const ns=activeNorthStar(s);return{deliverableId:d.id,title:d.title,goals:goals.map(g=>({id:g.id,title:g.title,description:g.description})),evidenceRefs:d.why?.evidenceRefs||[],constraints:(ns?.constraints||[]).filter(c=>(d.why?.constraintChecks||[]).some(x=>String(x).includes(c.text))||c.severity==='hard'),collaborators,assumptions:d.why?.assumptions||[],uncertainties:d.why?.uncertainties||[],decisionSummary:d.why?.decisionSummary||'',northStarVersion:d.why?.northStarVersion||null,agentPromptVersion:d.why?.agentPromptVersion||null};}
}
module.exports={DeliverableService};
