const {participantSchema,moderatorSchema}=require('../ai/schemas');
const prompts=require('../prompts');
const {now,activeNorthStar}=require('./helpers');

class MeetingService{
 constructor({stateManager,provider,eventService,usageService,deliverableService,approvalService,config}){Object.assign(this,{stateManager,provider,eventService,usageService,deliverableService,approvalService,config});this.busy=new Set();}
 list(){const s=this.stateManager.get();return(s.meetings||[]).filter(m=>m.companyId===s.activeCompanyId).sort((a,b)=>b.createdAt.localeCompare(a.createdAt));}
 get(id){const s=this.stateManager.get();return(s.meetings||[]).find(m=>m.companyId===s.activeCompanyId&&m.id===id)||null;}
 canStart(m){const s=this.stateManager.get(),done=new Set((s.tasks||[]).filter(t=>t.status==='done').map(t=>t.id));return(m.dependencyIds||[]).every(d=>done.has(d));}
 async start(meetingId){const m=this.get(meetingId);if(!m)throw Object.assign(new Error('Meeting not found.'),{status:404});if(this.busy.has(m.id))throw Object.assign(new Error('Meeting is already running.'),{status:409});if(!['scheduled','needs_input','failed'].includes(m.status))throw Object.assign(new Error('Meeting cannot start from its current state.'),{status:409});if(!this.canStart(m))throw Object.assign(new Error('Meeting dependencies are not finished yet.'),{status:409});this.busy.add(m.id);const s=this.stateManager.get();try{
  m.status='in_progress';m.startedAt=now();m.updatedAt=m.startedAt;this.eventService.append('meeting.started',{actor:{type:'system',id:'orchestrator'},entity:{type:'meeting',id:m.id},goalIds:m.goalIds,projectId:m.projectId,room:'meeting_room',payload:{participants:m.participantAgentIds}});await this.stateManager.persist();
  const northStar=activeNorthStar(s);const agents=(s.agents||[]).filter(a=>m.participantAgentIds.includes(a.id)&&a.status==='active');if(agents.length<2)throw new Error('Meeting needs at least two active participants.');
  const dependencyDeliverables=(m.dependencyIds||[]).map(tid=>s.tasks.find(t=>t.id===tid)?.deliverableId).filter(Boolean).map(id=>this.deliverableService.get(id)).filter(Boolean).map(d=>({id:d.id,title:d.title,content:d.versions?.find(v=>v.id===d.currentVersionId)?.content||''}));
  const contributions=[];
  for(const agent of agents.slice(0,4)){
   const prompt=prompts.meetingParticipant({agent,agenda:m.agenda,northStar,inputs:dependencyDeliverables});const r=await this.provider.generate({provider:agent.modelPolicy?.provider,model:agent.modelPolicy?.defaultModel,...prompt,responseSchema:participantSchema,metadata:{action:'meeting_participant',meetingId:m.id,agentId:agent.id},context:{agent,agenda:m.agenda,northStar,inputs:dependencyDeliverables}});this.usageService.record(r,{agentId:agent.id,projectId:m.projectId,meetingId:m.id,purpose:'meeting_participant'});const c={id:`con_${agent.id}_${Date.now()}`,agentId:agent.id,agentName:agent.displayName,role:agent.role,...r.data,createdAt:now()};contributions.push(c);this.eventService.append('meeting.contribution_added',{actor:{type:'agent',id:agent.id},entity:{type:'meeting',id:m.id},goalIds:m.goalIds,projectId:m.projectId,room:'meeting_room',payload:{contributionId:c.id}});
  }
  m.status='synthesizing';m.contributions=contributions;m.updatedAt=now();await this.stateManager.persist();
  const moderator=(s.agents||[]).find(a=>a.id===m.moderatorAgentId)||agents[0];const modPrompt=prompts.meetingModerator({agenda:m.agenda,northStar,contributions,outputContract:m.outputContract});const r=await this.provider.generate({provider:moderator.modelPolicy?.provider,model:moderator.modelPolicy?.defaultModel,...modPrompt,responseSchema:moderatorSchema,metadata:{action:'meeting_moderator',meetingId:m.id,agentId:moderator.id},context:{agenda:m.agenda,northStar,contributions,inputDeliverables:dependencyDeliverables,outputContract:m.outputContract}});this.usageService.record(r,{agentId:moderator.id,projectId:m.projectId,meetingId:m.id,purpose:'meeting_moderator'});const result=r.data||{};
  const content=[result.summary||'',...(result.agreements?.length?['','Agreements:',...result.agreements.map(x=>`- ${x}`)]:[]),...(result.disagreements?.length?['','Disagreements:',...result.disagreements.map(x=>`- ${x}`)]:[]),...(result.recommendations?.length?['','Recommendations:',...result.recommendations.map(x=>`- ${x}`)]:[])].join('\n').trim();
  const deliverable=this.deliverableService.create({title:result.deliverable?.title||m.title,type:result.deliverable?.type||m.outputContract?.type||'decision_record',content,structuredData:result,createdBy:{type:'agent',id:moderator.id},goalIds:m.goalIds,projectId:m.projectId,evidenceRefs:dependencyDeliverables.map(d=>`deliverable:${d.id}`),assumptions:contributions.flatMap(c=>c.assumptions||[]),uncertainties:result.unresolvedQuestions||[],goalAlignment:m.goalIds.map(x=>`goal:${x}`),constraintChecks:(northStar?.constraints||[]).map(c=>`Checked: ${c.text}`),collaboratorAgentIds:agents.map(a=>a.id),decisionSummary:result.summary||'',status:'needs_review',northStarVersion:northStar?.version||null,agentPromptVersion:moderator.promptVersion||1});
  m.deliverableId=deliverable.id;m.status='review';m.result=result;m.completedAt=now();m.updatedAt=m.completedAt;const approval=this.approvalService.request({entityType:'meeting',entityId:m.id,title:`Approve meeting decision: ${m.title}`,summary:result.summary||'Cross-functional decision requires human approval.',projectId:m.projectId,goalIds:m.goalIds,requestedBy:{type:'agent',id:moderator.id}});m.approvalId=approval.id;this.eventService.append('meeting.completed',{actor:{type:'agent',id:moderator.id},entity:{type:'meeting',id:m.id},goalIds:m.goalIds,projectId:m.projectId,room:'meeting_room',payload:{deliverableId:deliverable.id,approvalId:approval.id,participants:m.participantAgentIds}});await this.stateManager.persist();return m;
 }catch(error){m.status='failed';m.error=String(error.message||error).slice(0,1000);m.updatedAt=now();this.eventService.append('meeting.failed',{actor:{type:'system',id:'orchestrator'},entity:{type:'meeting',id:m.id},goalIds:m.goalIds,projectId:m.projectId,room:'meeting_room',payload:{participants:m.participantAgentIds,error:m.error}});await this.stateManager.persist();throw error;}finally{this.busy.delete(m.id);}}
 async approve(meetingId,approved=true,note=''){const m=this.get(meetingId);if(!m)throw Object.assign(new Error('Meeting not found.'),{status:404});if(m.status!=='review')throw Object.assign(new Error('Meeting is not waiting for review.'),{status:409});const a=m.approvalId&&this.approvalService.get(m.approvalId);if(a&&a.status==='pending')this.approvalService.resolve(a.id,approved?'approved':'rejected',note);m.status=approved?'completed':'needs_input';m.reviewNote=String(note||'').slice(0,3000);m.updatedAt=now();const d=m.deliverableId&&this.deliverableService.get(m.deliverableId);if(d)d.status=approved?'approved':'needs_revision';await this.stateManager.persist();return m;}
}
module.exports={MeetingService};
