const {standupSchema}=require('../ai/schemas');
const prompts=require('../prompts');
const {id,now}=require('./helpers');
class StandupService{
 constructor({stateManager,provider,eventService,usageService,config}){Object.assign(this,{stateManager,provider,eventService,usageService,config});}
 snapshot(){const s=this.stateManager.get(),cid=s.activeCompanyId;const agents=new Map((s.agents||[]).filter(a=>a.companyId===cid).map(a=>[a.id,a]));const tasks=(s.tasks||[]).filter(t=>t.companyId===cid);const meetings=(s.meetings||[]).filter(m=>m.companyId===cid);const approvals=(s.approvals||[]).filter(a=>a.companyId===cid&&a.status==='pending');const completed=tasks.filter(t=>t.status==='done').slice(-8).map(t=>({summary:`${agents.get(t.assigneeAgentId)?.displayName||'Agent'} completed “${t.title}”.`,ref:`task:${t.id}`}));const decisions=meetings.filter(m=>['review','completed'].includes(m.status)&&m.result?.summary).slice(-5).map(m=>({summary:m.result.summary,ref:`meeting:${m.id}`}));const needsAttention=[...approvals.map(a=>({priority:'high',summary:a.title,ref:`approval:${a.id}`})),...tasks.filter(t=>t.status==='review').map(t=>({priority:'medium',summary:`Review “${t.title}”.`,ref:`task:${t.id}`}))].slice(0,10);const blockers=tasks.filter(t=>['blocked','failed'].includes(t.status)).map(t=>({summary:`${t.title}: ${t.error||t.questions?.join(' ')||'blocked'}`,ref:`task:${t.id}`})).slice(0,10);const next=tasks.filter(t=>['queued','waiting_dependency'].includes(t.status)).slice(0,8).map(t=>({summary:`${t.status==='queued'?'Ready':'Waiting on dependencies'}: ${t.title}`,ref:`task:${t.id}`}));const usage=(s.usage||[]).filter(u=>u.companyId===cid);const total=usage.reduce((a,u)=>a+(u.totalTokens||0),0);return{generatedAt:now(),completed,decisions,needsAttention,blockers,next,usageSummary:usage.length?`${usage.length} model calls, ${total.toLocaleString()} total tokens recorded.`:'No paid model usage recorded in this workspace.'};}
 async generate(){const s=this.stateManager.get(),snapshot=this.snapshot(),prompt=prompts.standup({snapshot});const r=await this.provider.generate({...prompt,responseSchema:standupSchema,metadata:{action:'standup'},context:{snapshot}});this.usageService.record(r,{purpose:'standup'});const standup={id:id('std'),companyId:s.activeCompanyId,period:{end:snapshot.generatedAt},snapshot,summary:r.data,createdAt:now()};s.standups.push(standup);this.eventService.append('standup.generated',{actor:{type:'agent',id:'chief_of_staff'},entity:{type:'standup',id:standup.id},payload:{needsAttention:standup.summary?.needsAttention?.length||0}});await this.stateManager.persist();return standup;}
 get(idValue){const s=this.stateManager.get();return(s.standups||[]).find(x=>x.companyId===s.activeCompanyId&&x.id===idValue)||null;}
}
module.exports={StandupService};
