const {id,now,clean,activeAgents}=require('./helpers');
class TaskService{
 constructor({stateManager,eventService,deliverableService,approvalService,orchestrationService}){Object.assign(this,{stateManager,eventService,deliverableService,approvalService,orchestrationService});this.kick=()=>{};}
 setKick(fn){this.kick=fn||(()=>{});}
 list(){const s=this.stateManager.get(),agents=activeAgents(s);const names=new Map(agents.map(a=>[a.id,a.displayName]));return(s.tasks||[]).filter(t=>t.companyId===s.activeCompanyId).sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).map(t=>({...t,assignee:t.assignee||names.get(t.assigneeAgentId)||'Unassigned'}));}
 get(taskId){const s=this.stateManager.get();return(s.tasks||[]).find(t=>t.companyId===s.activeCompanyId&&t.id===taskId)||null;}
 resolveAgent(value){const s=this.stateManager.get(),agents=activeAgents(s);return agents.find(a=>a.id===value||a.displayName===value)||null;}
 async create(input={}){const s=this.stateManager.get(),title=clean(input.title,160),agent=this.resolveAgent(input.assigneeAgentId||input.assignee);if(!title||!agent)throw Object.assign(new Error('A task needs a title and an active assignee.'),{status:400});const createdAt=now();const task={id:id('tsk'),companyId:s.activeCompanyId,projectId:input.projectId||null,goalIds:Array.isArray(input.goalIds)?input.goalIds:[],title,brief:clean(input.brief||input.description,5000),description:clean(input.brief||input.description,5000),status:'queued',assigneeAgentId:agent.id,assignee:agent.displayName,collaboratorAgentIds:[],requiredSkills:[],requiredToolIds:[],dependencyIds:[],priority:50,approvalPolicy:input.approvalPolicy||'review_output',riskLevel:'low',northStarVersion:null,outputContract:input.outputContract||{type:'document'},runId:null,version:1,createdBy:{type:'user',id:'local-user'},createdAt,updatedAt:createdAt};s.tasks.push(task);this.eventService.append('task.created',{actor:task.createdBy,entity:{type:'task',id:task.id},goalIds:task.goalIds,projectId:task.projectId,payload:{title,assigneeAgentId:agent.id}});this.eventService.append('task.queued',{actor:{type:'system',id:'scheduler'},entity:{type:'task',id:task.id},goalIds:task.goalIds,projectId:task.projectId});await this.stateManager.persist();setImmediate(this.kick);return{...task,assignee:agent.displayName};}
 async answer(taskId,{answer,version}){const t=this.get(taskId);if(!t)throw Object.assign(new Error('Task not found.'),{status:404});if(t.status!=='blocked'||Number(version)!==(t.version||0))throw Object.assign(new Error('These questions changed. Refresh and answer the latest ones.'),{status:409});const text=clean(answer,3000);if(!text)throw Object.assign(new Error('Write an answer first.'),{status:400});t.brief=`${t.brief}\n\nQuestions:\n${(t.questions||[]).join('\n')}\n\nHuman answers:\n${text}`.trim().slice(0,5000);t.status='queued';delete t.questions;delete t.error;t.runId=null;t.version++;t.updatedAt=now();this.eventService.append('task.queued',{actor:{type:'user',id:'local-user'},entity:{type:'task',id:t.id},goalIds:t.goalIds,projectId:t.projectId,payload:{answered:true}});await this.stateManager.persist();setImmediate(this.kick);return t;}
 async review(taskId,{action,feedback='',version}){const t=this.get(taskId);if(!t)throw Object.assign(new Error('Task not found.'),{status:404});if(t.status!=='review'||Number(version)!==(t.version||0))throw Object.assign(new Error('This draft changed. Refresh and review the latest version.'),{status:409});if(action==='revise'&&!clean(feedback,5000))throw Object.assign(new Error('Describe the changes needed.'),{status:400});const s=this.stateManager.get();if(action==='approve'){t.status='done';t.reviewedAt=now();t.updatedAt=t.reviewedAt;t.version++;const d=t.deliverableId&&this.deliverableService.get(t.deliverableId);if(d){d.status='approved';d.updatedAt=now();this.eventService.append('deliverable.approved',{actor:{type:'user',id:'local-user'},entity:{type:'deliverable',id:d.id},goalIds:d.goalIds,projectId:d.projectId});}const a=(s.approvals||[]).find(x=>x.entityType==='task'&&x.entityId===t.id&&x.status==='pending');if(a)this.approvalService.resolve(a.id,'approved');this.eventService.append('task.completed',{actor:{type:'user',id:'local-user'},entity:{type:'task',id:t.id},goalIds:t.goalIds,projectId:t.projectId,payload:{approved:true}});this.orchestrationService.releaseDependencies();if(t.projectId)this.orchestrationService.updateProjectCompletion(t.projectId);}else{t.status='queued';t.feedback=clean(feedback,5000);t.runId=null;t.updatedAt=now();t.version++;const a=(s.approvals||[]).find(x=>x.entityType==='task'&&x.entityId===t.id&&x.status==='pending');if(a)this.approvalService.resolve(a.id,'revision_requested',t.feedback);this.eventService.append('task.revision_requested',{actor:{type:'user',id:'local-user'},entity:{type:'task',id:t.id},goalIds:t.goalIds,projectId:t.projectId,payload:{feedback:t.feedback}});}await this.stateManager.persist();setImmediate(this.kick);return t;}
 async reassign(taskId,value){const t=this.get(taskId),agent=this.resolveAgent(value);if(!t)throw Object.assign(new Error('Task not found.'),{status:404});if(!agent)throw Object.assign(new Error('Pick an active assignee.'),{status:400});t.assigneeAgentId=agent.id;t.assignee=agent.displayName;if(!['done','cancelled'].includes(t.status))t.status='queued';t.runId=null;t.error=undefined;t.version=(t.version||0)+1;t.updatedAt=now();this.eventService.append('task.reassigned',{actor:{type:'user',id:'local-user'},entity:{type:'task',id:t.id},goalIds:t.goalIds,projectId:t.projectId,payload:{assigneeAgentId:agent.id}});await this.stateManager.persist();setImmediate(this.kick);return t;}
 async retry(taskId){const t=this.get(taskId);if(!t)throw Object.assign(new Error('Task not found.'),{status:404});if(!['failed','queued'].includes(t.status))throw Object.assign(new Error('Only failed/queued tasks can be retried.'),{status:409});t.status='queued';delete t.error;t.runId=null;t.version=(t.version||0)+1;t.updatedAt=now();await this.stateManager.persist();setImmediate(this.kick);return t;}
}
module.exports={TaskService};
