const {id,now,clean,activeAgents}=require('./helpers');
const {reuseRequest}=require('./request-identity');
class TaskService{
 constructor({stateManager,eventService,deliverableService,approvalService,orchestrationService}){Object.assign(this,{stateManager,eventService,deliverableService,approvalService,orchestrationService});this.kick=()=>{};this.requests=new Map();this.changing=new Set();}
 setKick(fn){this.kick=fn||(()=>{});}
 list(){const s=this.stateManager.get(),agents=(s.agents||[]).filter(a=>a.companyId===s.activeCompanyId);const names=new Map(agents.map(a=>[a.id,a.displayName]));return(s.tasks||[]).filter(t=>t.companyId===s.activeCompanyId).sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).map(t=>({...t,assignee:names.get(t.assigneeAgentId)||t.assignee||'Unassigned'}));}
 get(taskId){const s=this.stateManager.get();return(s.tasks||[]).find(t=>t.companyId===s.activeCompanyId&&t.id===taskId)||null;}
 resolveAgent(value){const s=this.stateManager.get(),agents=activeAgents(s);return agents.find(a=>a.id===value||a.displayName===value)||null;}
 async create(input={}){const payload={title:clean(input.title,160),brief:clean(input.brief||input.description,5000),assignee:input.assigneeAgentId||input.assignee,approvalPolicy:input.approvalPolicy||'review_output',intakeMode:input.intakeMode||'manual',webResearch:Boolean(input.webResearch)};return reuseRequest({stateManager:this.stateManager,collection:'tasks',pending:this.requests,input,payload,create:metadata=>this.createTask(input,metadata)});}
 async createTask(input={},metadata={}){const s=this.stateManager.get(),title=clean(input.title,160),agent=this.resolveAgent(input.assigneeAgentId||input.assignee);if(!title||!agent)throw Object.assign(new Error('A task needs a title and an active assignee.'),{status:400});const createdAt=now(),intakeMode=clean(input.intakeMode,40)==='direct_agent'?'direct_agent':input.projectId?'mission_task':'manual';const task={...metadata,id:id('tsk'),companyId:s.activeCompanyId,projectId:input.projectId||null,goalIds:Array.isArray(input.goalIds)?input.goalIds:[],title,brief:clean(input.brief||input.description,5000),description:clean(input.brief||input.description,5000),status:'queued',webResearch:Boolean(input.webResearch),assigneeAgentId:agent.id,assignee:agent.displayName,intakeMode,collaboratorAgentIds:[],requiredSkills:[],requiredToolIds:[],dependencyIds:[],priority:50,approvalPolicy:input.approvalPolicy||'review_output',riskLevel:'low',northStarVersion:null,outputContract:input.outputContract||{type:'document'},runId:null,version:1,createdBy:{type:'user',id:'local-user'},createdAt,updatedAt:createdAt};const eventIds=new Set((s.events||[]).map(e=>e.id));s.tasks.push(task);this.eventService.append('task.created',{actor:task.createdBy,entity:{type:'task',id:task.id},goalIds:task.goalIds,projectId:task.projectId,payload:{title,assigneeAgentId:agent.id,intakeMode}});this.eventService.append('task.queued',{actor:{type:'system',id:'scheduler'},entity:{type:'task',id:task.id},goalIds:task.goalIds,projectId:task.projectId});try{await this.stateManager.persist();}catch(error){s.tasks=s.tasks.filter(t=>t.id!==task.id);s.events=s.events.filter(e=>eventIds.has(e.id)||e.entity?.id!==task.id);throw error;}setImmediate(this.kick);return{...task,assignee:agent.displayName};}
 async persistMutation(task,related,mutate){
  if(this.changing.has(task.id))throw Object.assign(new Error('This task is being updated.'),{status:409});
  this.changing.add(task.id);const state=this.stateManager.get(),snapshots=[...new Set([task,...related].filter(Boolean))].map(record=>({record,before:structuredClone(record)})),previousEvents=new Set(state.events.map(event=>event.id));let addedEvents;
  try{mutate();addedEvents=new Set(state.events.filter(event=>!previousEvents.has(event.id)).map(event=>event.id));await this.stateManager.persist();setImmediate(this.kick);return task;}
  catch(error){for(const {record,before} of snapshots){for(const key of Object.keys(record))delete record[key];Object.assign(record,before);}addedEvents||=new Set(state.events.filter(event=>!previousEvents.has(event.id)).map(event=>event.id));state.events=state.events.filter(event=>!addedEvents.has(event.id));throw error;}
  finally{this.changing.delete(task.id);}
 }
 async answer(taskId,{answer,version}){
  const t=this.get(taskId);if(!t)throw Object.assign(new Error('Task not found.'),{status:404});if(t.status!=='blocked'||Number(version)!==(t.version||0))throw Object.assign(new Error('These questions changed. Refresh and answer the latest ones.'),{status:409});const text=clean(answer,3000);if(!text)throw Object.assign(new Error('Write an answer first.'),{status:400});
  return this.persistMutation(t,[],()=>{t.brief=`${t.brief}\n\nQuestions:\n${(t.questions||[]).join('\n')}\n\nHuman answers:\n${text}`.trim().slice(0,5000);t.status='queued';delete t.questions;delete t.error;t.runId=null;t.version++;t.updatedAt=now();this.eventService.append('task.queued',{actor:{type:'user',id:'local-user'},entity:{type:'task',id:t.id},goalIds:t.goalIds,projectId:t.projectId,payload:{answered:true}});});
 }
 async review(taskId,{action,feedback='',version}){
  const t=this.get(taskId);if(!t)throw Object.assign(new Error('Task not found.'),{status:404});if(t.status!=='review'||Number(version)!==(t.version||0))throw Object.assign(new Error('This draft changed. Refresh and review the latest version.'),{status:409});if(!['approve','revise'].includes(action))throw Object.assign(new Error('Choose approve or revise.'),{status:400});if(action==='revise'&&!clean(feedback,5000))throw Object.assign(new Error('Describe the changes needed.'),{status:400});
  const state=this.stateManager.get(),deliverable=t.deliverableId&&this.deliverableService.get(t.deliverableId),approval=state.approvals.find(item=>item.companyId===t.companyId&&item.entityType==='task'&&item.entityId===t.id&&item.status==='pending'),project=state.projects.find(item=>item.companyId===t.companyId&&item.id===t.projectId),goals=state.goals.filter(item=>project?.goalIds?.includes(item.id)),waiting=state.tasks.filter(item=>item.companyId===t.companyId&&item.status==='waiting_dependency');
  return this.persistMutation(t,[deliverable,approval,project,...goals,...waiting],()=>{
   if(action==='approve'){t.status='done';t.reviewedAt=now();t.updatedAt=t.reviewedAt;t.version++;if(deliverable){deliverable.status='approved';deliverable.updatedAt=now();this.eventService.append('deliverable.approved',{actor:{type:'user',id:'local-user'},entity:{type:'deliverable',id:deliverable.id},goalIds:deliverable.goalIds,projectId:deliverable.projectId});}if(approval)this.approvalService.resolve(approval.id,'approved');this.eventService.append('task.completed',{actor:{type:'user',id:'local-user'},entity:{type:'task',id:t.id},goalIds:t.goalIds,projectId:t.projectId,payload:{approved:true}});this.orchestrationService.releaseDependencies();if(t.projectId)this.orchestrationService.updateProjectCompletion(t.projectId);}
   else{t.status='queued';t.feedback=clean(feedback,5000);t.runId=null;t.updatedAt=now();t.version++;if(approval)this.approvalService.resolve(approval.id,'revision_requested',t.feedback);this.eventService.append('task.revision_requested',{actor:{type:'user',id:'local-user'},entity:{type:'task',id:t.id},goalIds:t.goalIds,projectId:t.projectId,payload:{feedback:t.feedback}});}
  });
 }
 async reassign(taskId,value){
  const task=this.get(taskId),agent=this.resolveAgent(value);
  if(!task)throw Object.assign(new Error('Task not found.'),{status:404});
  if(!agent)throw Object.assign(new Error('Pick an active assignee.'),{status:400});
  if(!['queued','waiting_dependency','blocked','failed'].includes(task.status))throw Object.assign(new Error('Only queued, waiting, blocked, or failed work can be reassigned.'),{status:409});
  if(this.changing.has(taskId))throw Object.assign(new Error('This task is being updated.'),{status:409});
  this.changing.add(taskId);const state=this.stateManager.get(),original=structuredClone(task);
  const dependencies=(task.dependencyIds||[]).map(id=>state.tasks.find(item=>item.companyId===task.companyId&&item.id===id));
  task.assigneeAgentId=agent.id;task.assignee=agent.displayName;task.status=dependencies.some(item=>!item||item.status!=='done')?'waiting_dependency':'queued';task.runId=null;delete task.error;delete task.questions;task.version=(task.version||0)+1;task.updatedAt=now();
  const event=this.eventService.append('task.reassigned',{actor:{type:'user',id:'local-user'},entity:{type:'task',id:task.id},goalIds:task.goalIds,projectId:task.projectId,payload:{assigneeAgentId:agent.id}});
  try{await this.stateManager.persist();setImmediate(this.kick);return task;}catch(error){for(const key of Object.keys(task))delete task[key];Object.assign(task,original);state.events=state.events.filter(item=>item.id!==event.id);throw error;}finally{this.changing.delete(taskId);}
 }
 async retry(taskId){const t=this.get(taskId);if(!t)throw Object.assign(new Error('Task not found.'),{status:404});if(!['failed','queued'].includes(t.status))throw Object.assign(new Error('Only failed/queued tasks can be retried.'),{status:409});return this.persistMutation(t,[],()=>{t.status='queued';delete t.error;t.runId=null;t.version=(t.version||0)+1;t.updatedAt=now();});}
}
module.exports={TaskService};
